spring.application.name=taskmanager

spring.data.mongodb.uri=mongodb+srv://akshat:Redcow%40123@cluster0.px7njnq.mongodb.net/taskmanager?retryWrites=true&w=majority
gemini.api.key=AQ.Ab8RN6KF9E-sop-dDx8AEZgOHV4SVPJNTkCeAynUEIGZCsOcGg